[package]
name = "sleipnir_plugin_agents"
version = "0.1.0"
edition.workspace = true
publish = false
license.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[[bin]]
name = "sleipnir-plugin-agents"
path = "src/main.rs"

[dependencies]
sleipnir-plugin.workspace = true
agent_coordination.workspace = true
uuid.workspace = true

[dev-dependencies]
plugin_host.workspace = true
serde_json.workspace = true
