[package]
name = "sleipnir_ctl"
version = "0.1.0"
edition.workspace = true
publish = false
license.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[[bin]]
name = "sleipnir-ctl"
path = "src/bin/sleipnir-ctl.rs"

[dependencies]
dirs.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
