[package]
name = "sleipnir_ui"
version = "0.1.1"
edition.workspace = true
publish = false
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/sleipnir_ui.rs"

[dependencies]
collections.workspace = true
dirs.workspace = true
gpui.workspace = true
terminal.workspace = true
sleipnir_settings.workspace = true
release_channel.workspace = true
updater.workspace = true
itertools.workspace = true
log.workspace = true
util.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true
run_ledger.workspace = true

[target.'cfg(target_os = "linux")'.dependencies]
notify-rust = "4"

[dev-dependencies]
tempfile.workspace = true
