[package]
name = "jiajia_term_ui"
version = "0.1.0"
edition.workspace = true
publish = false
license = "GPL-3.0-or-later"

[lints]
workspace = true

[lib]
path = "src/jiajia_term_ui.rs"

[dependencies]
collections.workspace = true
dirs.workspace = true
gpui.workspace = true
terminal.workspace = true
jiajia_settings.workspace = true
itertools.workspace = true
log.workspace = true
util.workspace = true
