[package]
name = "run_ledger"
version = "0.1.0"
edition.workspace = true
publish = false
license.workspace = true

[lints]
workspace = true

[lib]
doctest = false

[dependencies]
atomic_write.workspace = true
plugin_protocol.workspace = true
serde.workspace = true
serde_json.workspace = true
uuid.workspace = true

[dev-dependencies]
tempfile.workspace = true
