[package]
name = "sleipnir"
version = "0.1.10"
edition.workspace = true
publish = false
license = "GPL-3.0-or-later"

[lints]
workspace = true

[[bin]]
name = "sleipnir"
path = "src/main.rs"

[dependencies]
env_logger.workspace = true
gpui = { workspace = true, features = ["font-kit"] }
gpui_platform = { workspace = true, features = ["font-kit"] }
sleipnir_settings.workspace = true
sleipnir_ui.workspace = true
release_channel.workspace = true
terminal.workspace = true
log.workspace = true
